sudo: no
language: python

python:
  - "3.6"
  - "nightly"

cache:
  directories:
  - $HOME/.cache/pip


before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


install:
  - pip install --upgrade pip wheel setuptools
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - flake8 scripts
  - py.test --cov=scripts tests
  - python setup.py check -rm
